### ISSUE TITLE
Prestanu raditi h/f

### ISSUE THREAD

**Issue by sasadj1** [wssto2/renault-header-footer-2022#3]
Joža,
danas smo skužili da h/f prestanu raditi (očito sami od sebe). Pa je Grga skužio da ovo ne radi: https://unpkg.com/@wssto2/renault-header-footer-2022/dist/js/chunk-vendors.js
![image](https://user-images.githubusercontent.com/72204614/229895163-38cf584f-a9b7-4532-8eb5-3407da756dd6.png)

Imamo li šta napraviti po tom pitanju? Jerbo mi se čini da ne radi već sigurno pola sata...

Tnx,
Saša.

**Comment by antesto2** [comment]
samo mali komentar, ovo nije prvi put, meni se znalo tako dogodit da se ne prikazuje pa se onda kroz par sati oporavi. mozda bi trebalo razmislit o nekom drugom service-u
